services:
  api:
    build: .
    container_name: api
    network_mode: bridge
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/www
      - ./clases:/var/www/html/clases
      - ./vendor:/var/www/html/vendor
      - ./cache:/var/www/html/cache
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
